apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: api
    image: demo:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8000
    env:
    - name: REDIS_ADDR
      value: redis:6379
